multiprocessing_strategies:

    rc_disable_pbar: True
    num_workers: 16
    load_cache_data: True
    boards_per_centipawn: 25
    board_weight_90th_percentile: 10_000
    
    score_config:
        capture_king_score: 50_000
        checkmate_score: 30_000
        into_check_score: -40_000
        reward_attacker: 300
        search_depth: 8

    move_config:
        mean_score_factor: 0.9
        min_score_factor: 0.1
        max_score_factor: 0.0

    time_config:
        turns_to_plan_for: 20
        time_for_sense: 0.8
        time_for_move: 0.15

rc_disable_pbar: True
pool_size: 16
